import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css'
import SteelDoorNav from '../../components/server/SteelDoorNav';
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'SteelDoor web app',
  description: 'Generated by Julio Bonatti',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-bs-theme="dark" >
      <body className={inter.className}>
        <SteelDoorNav />
        {children}
      </body>
    </html>
  )
}
